### ISSUE TITLE
Section state is not preserved in route information view

### ISSUE THREAD

**Issue by dittaeva** [lonvia/waymarked-trails-site#136]
Was hard to describe this short, but do this and you see what I mean:

1. Open the route information view for a route which can show elevation profile.
2. Open the elevation profile section and close the OpenStreetMap tags section.
3. Zoom in on the route with the zoom to route button.

After no. three the elevation profile section will be closed again and the tags section open again.

**Comment by lonvia** [comment]
We no longer permalink via Zoom, which fixes this issue.
