### ISSUE TITLE
Not able to scroll on mobile

### ISSUE THREAD

**Issue by esisa** [lonvia/waymarked-trails-site#138]
I am not able to scroll search or info views on my mobile phone. I am using Chrome 18 on Android 4.2.

**Comment by jschleic** [comment]
The move to CherryPy changed the css, probably this isssue is fixed now (5010d8b)?
I can scroll within the sidebar using Chrome 52.

**Comment by lonvia** [comment]
Indeed, jquery-mobile should handle overflow differently. If somebody runs into a similar issue, open a new issue.
