### ISSUE TITLE
Welcome page with route type chooser

### ISSUE THREAD

**Issue by dittaeva** [lonvia/waymarked-trails-site#146]
Cycling seems to be the most popular route type on waymarkedtrails, yet when you go to waymarkedtrails.org you'll be redirected to hiking.waymarkedtrails.org.

That there are different route types available should be highlighted better. I don't know what would be the best way, but an easy way seems to be to put a javascript overlay with big buttons for each route type when users go directly to waymarkedtrails.org. Could use the same javascript as in issue #113.

**Comment by lonvia** [comment]
Now available on waymarkedtrails.org (without a subdomain).
