### ISSUE TITLE
Route drawing ignores colour=* tag

### ISSUE THREAD

**Issue by andrewerrington** [lonvia/waymarked-trails-site#161]
Is it possible to make the renderer use the colour specified in the colour=* tag, if present?

Here are some routes in Korea that I made:
http://hiking.waymarkedtrails.org/en/?zoom=15&lat=35.726&lon=127.94932&route=1&hill=0.82#routes

Here is something that Koreans expect to see (click on one of the entries in the box on the left and a coloured route line will be drawn):
http://tour1.geochang.go.kr/gmap/main_map.asp?mj=1

Signboards at the bottom of each route have maps with the same coloured lines as the on-line map.

Perhaps there could be an option in 'preferences' for whether to use colour=* if present, or the default purple?

Thank you.

**Comment by lonvia** [comment]
color is now shown as an underline in the normal ref symbol, e.g. http://cycling.waymarkedtrails.org/#?map=13!51.9791!16.9354 This works for cycling and hiking for now. The symbols are slightly larger, we'll see how that works out.

I've only updated the symbols in the cycling map, hiking routes will only be affected when they are changed.

**Comment by gorn** [comment]
Sorry, this is not what I ment. If you want I can file a new issue or please reopen (or reject) this one. I have explained it above and is emails, but briefly - this is about the color of the line. There is well thought system of colouring system in Czechia and people here are very used to them. Currently the coloring of the map is very confusing to them. More details above.
