### ISSUE TITLE
Info and Search buttons overlap on very small mobile screeens

### ISSUE THREAD

**Issue by lonvia** [lonvia/waymarked-trails-site#162]
Now that we have five buttons in the footer, there is no longer enough space for all of them on my old test Samsung. Not sure if that still can become an issue on more modern phones. Still, look into replacing the text buttons with icon buttons for very small screens.

**Comment by jschleic** [comment]
Is this still an issue? In english the buttons seem fine now at a width of 300px.

I've implemented the search-symbol using jquery-ui; they don't have a zigzag. is there an appropriate symbol you want to use for the routes?

**Comment by lonvia** [comment]
It's probably hard to find a mobile with less than 400px width but symbols are still nicer for the small screen. Looking at http://api.jquerymobile.com/icons/, I find the 'bullets' icon most appropriate.

**Comment by jschleic** [comment]
Use the bullets icon for the small size or in general? Or would it make sense to show Icon plus Text for the icons, when the window is larger and icon-only for lower widths?

**Comment by lonvia** [comment]
I would leave it as it is now. I don't think additional icons bring much information on larger screens.

**Comment by lonvia** [comment]
I've actually noticed only now that it does not switch back to text button anymore. I actually meant that I would go for text-only button on large screens. I find the text less ambigious.

**Comment by jschleic** [comment]
Ah, okay. So I use the bullet icon for the small size and keep the "Routes" for full width. Right?
I'll prepare another PR.
