### ISSUE TITLE
Route list and info box should cover the whole map area(?)

### ISSUE THREAD

**Issue by dittaeva** [lonvia/waymarked-trails-site#165]
At least on smaller screens the route info and list box should cover the whole map area. As it is now on my iPhone 4S there are only a fex pixels of map between the box and the edge of the screen, and these pixels serve no purpose.

If the box would cover the whole available area there'd be more space for the info in the boxes, and probably give a cleaner look. However, it might not work well on bigger screens (tablets), and could make the user experience somewhat non-uniform (boxes/fill between header and footer).

If the zoom area was subsequently limited to the area below the box header, using zoom and then minimising the box would give the user a better view.

**Comment by lonvia** [comment]
I still prefer the margin, so that's a won't fix.
