### ISSUE TITLE
Route ID in permalink

### ISSUE THREAD

**Issue by FrViPofm** [lonvia/waymarked-trails-site#167]
Hi,
Thanks for this usefull tool.
It would be nice, when a route is selected in the routes box, to get its id in the permalink. So it should be possible to share a link hiliting it.
Something like : http://hiking.waymarkedtrails.org/fr/?lat=44.69804&lon=3.1723&zoom=9&layers=TFBTFF#2918033

**Comment by lonvia** [comment]
Constantly updated browser URL now includes that.
