### ISSUE TITLE
Error when ismobile=true and you are not on a touch device

### ISSUE THREAD

**Issue by esisa** [lonvia/waymarked-trails-site#176]
The OpenLayers code is loaded depending on the value of ismobile, but the setup of Openlayers in Map.js is dependent on the value of Modernizr.touch.  Thus you get an error since the mobile version of OpenLayers is loaded:
OpenLayers.Control.Navigation is not a constructor

I guess that users that for example have a Blackberry would just get an error when entering the site. Although I do not know how the ismobile value is actually set.

**Comment by lonvia** [comment]
No longer applicable.
