### ISSUE TITLE
paths and tracks renderings are indistinguishable (OSM issue)

### ISSUE THREAD

**Issue by a-pirard** [lonvia/waymarked-trails-site#191]
This is not an issue regarding Waymarked directly but to let you know that I opened
https://github.com/gravitystorm/openstreetmap-carto/issues/547
because distinguishing paths and ways is important for hiking usage of the map.
I thought it would be interesting to find this here if you want to comment that issue there.
I'll take care of removing this entry when the issue evolves.

**Comment by lonvia** [comment]
This really is outside the scope of this tracker.
