### ISSUE TITLE
osmc:symbol label length limited to 3 digits

### ISSUE THREAD

**Issue by FabC** [lonvia/waymarked-trails-site#199]
When using osmc:symbol tag, the text label value is limited to 3 chars. Longer refs (e.g. "134c") are just not displayed. Example of not displayed symbol:

red:red:white_stripe:134c:black

URL: http://hiking.waymarkedtrails.org/it/?zoom=17&lat=43.51111&lon=10.3666&hill=0.49&base=0.51&route=0.89#routes

![image](https://cloud.githubusercontent.com/assets/2143554/4174786/61f4014e-35a8-11e4-8f00-4e7f04d4f150.png)

Thanks!

**Comment by lonvia** [comment]
I've changed the code to allow 4 characters as a maximum in osmc:symbols and stretched the symbol slightly for shields with 3 to 4 characters. Lets see how that turns out on the map.

**Comment by FabC** [comment]
Now it looks great for me:

![image](https://cloud.githubusercontent.com/assets/2143554/6880679/036ee2d8-d53f-11e4-81ba-1b957ebf0523.png)

Many Thanks!
