### ISSUE TITLE
GPX not ordered

### ISSUE THREAD

**Issue by lonvia** [lonvia/waymarked-trails-site#2]
If a route is incomplete or consists of separate sections, then the sections are not ordered in the GPX file.

See rel2gpx.pl script for how this could be done.

**Comment by Hufkratzer** [comment]
This doesn't seem to be solved to me. Take  route http://ra.osmsurround.org/analyzeMap?relationId=3976770 which is incomplete and consists of separate sections (has gaps) but the sections still do not seem to be (properly) ordered in the GPX file; shouldn't the last point before a gap be followed by the next point after the gap? This is not the case, as you can see when you import the gpx file from waymarkedtrails into RouteConverter:
![sskgpx](https://cloud.githubusercontent.com/assets/5958184/15729365/ccd14cf6-2863-11e6-8316-f2c8a0d10bf9.jpg)

**Comment by lonvia** [comment]
I have not regenerated the database (yet). The code has only an affect on updated relations.

**Comment by lonvia** [comment]
Still not activated due to a bug that is a bit difficut to track.

**Comment by lonvia** [comment]
The recently introduced reimplementation of the code seems to run stable now. Please be aware that 

 * routes are now ordered by the order they appear in the relation. If the relation is not ordered, the GPX will still not be ordered.
 * the database has not been reimported, only updated relations are affected by the change.

**Comment by Hufkratzer** [comment]
What is the reason for the first restriction? Is it a logical problem to order the subrelations automatically or is it just not implemented?

**Comment by lonvia** [comment]
For most relations there is no one clear order. Even complete relations that form exactly one continuous line have two possible solutions. So it's better to let the mapper decide. Keeping your relations in order is good practice anyway and easy to do with JOSM.
