### ISSUE TITLE
Add hexagon as symbol

### ISSUE THREAD

**Issue by StijnRR** [lonvia/waymarked-trails-site#205]
In Belgium some hiking routes are marked with a hexagon (usually yellow), e.g.: http://www.rlkm.be/nl/kempen-broek/startplekken/smeetshof-en-wijffelterbroek/wandelen. Is it possible to add the hexagon as foreground symbol?

**Comment by lonvia** [comment]
I've added a regular hexagon as a symbol but at the current symbol size it looks very much like a circle, so I'm not sure how much use it will be. Map still needs to be redrawn before the symbols will appear in older relations. That should happen some time this week.

**Comment by Eebie** [comment]
Indeed it looks like a circle on the map. It looks the same as symbol 'dot'. 
I am mapping in the same region as StijnRR. In our region it is an elongated (long) yellow hexagon that is used to mark some hiking routes. See ![hexagon_long_y](https://cloud.githubusercontent.com/assets/11687037/6878227/8f926ce0-d4da-11e4-8e64-b9fec7abad48.png). Can you add this symbol?
I contacted you some time ago too with the request to add this hexagon as foreground symbol. I got the reaction that I had to proove that the hexagon symbol is used. Meanwhile I did a some hiking route with that symbol. See https://taginfo.openstreetmap.org/keys/osmc%3Asymbol  and use value Hexagon.

**Comment by lonvia** [comment]
This elongated hexagon is rather special. I think it's best to add this at some point as a special regional rendering for the Netherlands. But implementing is going to take a while.
