### ISSUE TITLE
Tunnels

### ISSUE THREAD

**Issue by jrickards** [lonvia/waymarked-trails-site#209]
It would be nice to add the location, length, bike banned/allowed, alternate routes, lighting, road conditions and other information about tunnels in Norway (and any other location for that matter). Much of this information is at http://www.cycletourer.co.uk/maps/tunnelmap.shtml, it would just mean transferring it over to this site.

**Comment by lonvia** [comment]
This is really not the right site to do this and I'm not sure if this information is completely available in OSM.
