### ISSUE TITLE
Regeneration of tiles on guidepost change

### ISSUE THREAD

**Issue by wmaurer** [lonvia/waymarked-trails-site#212]
When a relation is changed, the waymarkedtrails tiles are regenerated, but when just a guidepost is changed, the tiles are not regenerated. I just undeleted some guideposts that someone had removed, and the tiles have not been regenerated:
http://www.waymarkedtrails.org/en/?zoom=17&lat=46.95454&lon=7.36873&hill=0.665#

Thanks
-Wayne

**Comment by lonvia** [comment]
This was intentional to keep the load manageable. With more server power and improved software it is something to be reevaluated.

**Comment by lonvia** [comment]
Should work now after the server upgrade.
