### ISSUE TITLE
Vennbahn cycling route is cut in pieces

### ISSUE THREAD

**Issue by Leongard** [lonvia/waymarked-trails-site#213]
The Vennbahn cycling route is cut in pieces, some of them overlapping. Overall length is longer than the real path.
As a major (cycling) mapper on OSM I think that things are OK there.

This problem is fairly new. Before ist was OK. Length was 122 km.

**Comment by lonvia** [comment]
This looks rather bad. It might just be an artifact of a recent screwup in the database updates in which case it will be necessary to rebuild the entire database. I'd like to investigate a bit deeper first to ensure there are no bugs in the code.

**Comment by lonvia** [comment]
I've reimported the database now which has fixed the issue. Possibly really just a temporary issue with the updates.
