### ISSUE TITLE
Old Hiking nodes still visible

### ISSUE THREAD

**Issue by JanWd** [lonvia/waymarked-trails-site#214]
Old hiking nodes which do not exist anymore are still visible.
Example via link:
http://hiking.waymarkedtrails.org/en/?zoom=16&lat=51.39151&lon=5.97588&hill=0

The hiking nodes "??" (2x questionmark) are visible on the map (route 45-59)
They are not in the osm data anymore.

**Comment by lonvia** [comment]
This is essentially the same as #212. Hiking nodes are not causing an update by themselves. I'll revisit that policy with the next software update.

Closing as duplicate.
