### ISSUE TITLE
Invalid GPX file created when a coordinate is very small

### ISSUE THREAD

**Issue by tvage** [lonvia/waymarked-trails-site#217]
GPX files that contain coordinate values that are smaller then 0.0001 are incorrectly created in exponential format instead of decimal. This then fails to validate against the GPX XSD and hence fails to load in some readers.

e.g.
            <trkpt lat="51.4864858" lon="-0.000377400000006"/>
            <trkpt lat="51.4865707" lon="-4.80000000117e-05"/>
            <trkpt lat="51.4866424" lon="0.0002498"/>

There are examples in the Thames Path GPX file.

**Comment by lonvia** [comment]
Fix is live now. A side-effect of the fix is that numbers where the decimal part is 0 will be rendered as integers (e.g. 23.00000 -> 23). Looks like the GPX XSD spec is ok with that.

**Comment by tvage** [comment]
Hi, thanks for the extremely quick fix – I was amazed to receive your email saying a fix was live so soon after I’d posted the issue.

 

Cheers,

Mike
