### ISSUE TITLE
Transparent "Routes in area" panel

### ISSUE THREAD

**Issue by Hufkratzer** [lonvia/waymarked-trails-site#222]
The panel titled "Routes in area" (list of routes) hides a part of the map and often a highlighted route so that one cannot see it and has to guess where it is. Perhaps it is possible and better to make the background of this panel transparent.

**Comment by lonvia** [comment]
I would prefer to go the other way around and restrict the listed routes to the part of the map that is visible. Still need to figure out how to get the necessary info out of javascript.

**Comment by Hufkratzer** [comment]
Now there are also routes in the list that are hidden by the title panel ("Waymarked Trails: ...") or by the panel at the bottom. I am not sure if this was better before the last update, but I think it was.

**Comment by KrilleGH** [comment]
When the routes panel is opened (i. e. it was closed when clicking the Routes button) it still shows routes which are hidden by it. The visible area seems to be calculated before the panel opens, moving the map a tiny bit after the panel is open makes these routes dissapear.

So it would be useful to first open the (empty) panel and then calculate the visible area.
