### ISSUE TITLE
support symbols for cycle routes

### ISSUE THREAD

**Issue by Hufkratzer** [lonvia/waymarked-trails-site#223]
Why aren't symbols supported for cycle routes? I assume the reason is just that osmc:symbol was invented by wanderreitkarte.de and this does not show cycle routes at all (just hiking and horse). But waymarkedtrails.org shows cycle routes, so why not support osmc:symbol there?

As an example take the polish cycle routes, they are marked as you can see here:
https://pl.wikipedia.org/wiki/Szlak_rowerowy
As you can see, there is a small bike on a white background underlined by a thick coloured dash. For the dash one could use the existing foreground symbols %color%_lower, for the background, as you do not support a second foreground, you can perhaps provide a new background symbol "black_bike" or so. I think This may encourage the Poles to use your overlays for their cycle routes, otherwise the different colours cannot be seen on the map.

For Norwich (UK) you use the colour tag to generate a symbol. You could also do that for Poland (they also often use the colour tag), but I would rather support osmc:symbol instead (everywhere) because there will always be exceptions from general rules and nobody can know and handle them all.

The same may apply to MTB routes, but I don't know many.

Compoare issue https://github.com/lonvia/waymarked-trails-site/issues/161

**Comment by lonvia** [comment]
osmc:color is not supported for cycling routes because nobody really asked for it. When people have asked for special rendering, they always found that osmc:color is not the right solution. I tend to agree with that. So until somebody has a good counterexample, this is a wontfix.

For Poland and other color-coded systems there is now support for the color tag, see #161.

**Comment by tsmcgrath** [comment]
In #432 (duplicate) @lonvia asked for a specific example of both a hiking and MTB trail. The Deschutes River trail is one such example. There are many and it is not exceptional for a trail to be 1) Hiker; 2) Mountain Bike; 3) Equestrian in the US.
https://hiking.waymarkedtrails.org/#route?id=9740591&type=relation&map=15.0/45.5325/-120.8804

**Comment by amadvance** [comment]
The most prominent example I know is the Italian national "Sentiero Italia" (about 8000km) that has both Hiking and MTB version. The root relation for the MTB version is not yet mapped (it's work in progress) but most of the stages are. 

Hiking: https://hiking.waymarkedtrails.org/#route?id=1021025
MTB: (just one of the many mapped stages) https://mtb.waymarkedtrails.org/#route?id=14944643

Another finished example is the "Sentiero dei Laghi". 

Hiking: https://hiking.waymarkedtrails.org/#route?id=14734665
MTB: https://mtb.waymarkedtrails.org/#route?id=15479395
