### ISSUE TITLE
(re)moved nodes of cycle/walking node networks

### ISSUE THREAD

**Issue by StijnRR** [lonvia/waymarked-trails-site#224]
When a osm-node loses its rwn_ref of rcn_ref tag and is removed from the corresponding relation, it is still visualised as a node of the node network. E.g. [here](http://cycling.waymarkedtrails.org/nl/?zoom=17&lat=51.00022&lon=5.70608&hill=0): the rwn_tags have been removed more than a year ago, but the numbers 55 are still there. I thought removing the osm-node completely should be a workaround to solve the problem. But then I noticed [this solitary nr 69](http://cycling.waymarkedtrails.org/nl/?zoom=17&lat=50.91332&lon=5.54121&hill=0) (the one to the left of the bridge). There isn't even a osm-node anymore at that location...

**Comment by lonvia** [comment]
Looks fixed in the new version which will go live in a couple of days.

**Comment by StijnRR** [comment]
Indeed, it's fixed. Thanks!
