### ISSUE TITLE
titlebar too small with screen lower resolution 

### ISSUE THREAD

**Issue by Hufkratzer** [lonvia/waymarked-trails-site#226]
With screen resolution 800x600 the icons do no longer fit in the titlebar, the titlebar seems to be too small, at least in Firefox, Chrome and Opera:
![header](https://cloud.githubusercontent.com/assets/5958184/14066314/828cf6aa-f446-11e5-8678-24ae7ca51d38.jpg)

This was not so until about 10 days ago.

**Comment by Hufkratzer** [comment]
What a strange fix! How is one supposed to switch between hiking, cycling, riding ... without the buttons? As I wrote initially, it was ok until February; why not make it as it once was?

**Comment by jschleic** [comment]
The map is the main focus of the site. For devices with low resolution (e.g. smartphones) the header would consume too much height, so its height is reduced to show as many routes as possible. Smaller hiking, cycling, ... buttons would fit at 700px width, but not at 400px width.
How to switch beween the map variants is another question. I opened a new issue #251 to discuss that.
