### ISSUE TITLE
Allow setting the hillshading in the URL

### ISSUE THREAD

**Issue by KrilleGH** [lonvia/waymarked-trails-site#227]
The old version of the site allowed to set the opacity of the hillshading layer in the URL. This is useful for bookmarks or sharing links. Please add it back.

**Comment by lonvia** [comment]
Sorry but that's unlikely to come back. If and how much hillshading is displayed should be a matter of personal preference, so it's saved in local storage now. The same is true for language preferences by the way.

**Comment by KrilleGH** [comment]
Well, I often put links to routes on hiking event pages or send them to people. They don't know about the site and that there is an option to enable hillshading. They just want a nice map. With the hillshading parameter in the URL it was possible to provide a single click solution.

**Comment by lonvia** [comment]
Alright, I've reintroduced the hill parameter as a secret parameter which you can manually add when sharing links, e.g. http://hiking.waymarkedtrails.org/#route?id=132518&map=10!46.1056!7.2427&hill=0.4

Note that it has no influence on the individual settings of the user. Once they come back using a link without the hill parameter, the previous user-defined settings will be back.

**Comment by KrilleGH** [comment]
That's fine, thanks!

**Comment by Stefal** [comment]
Do you think it's possible to add other settings as hidden parameters ?
Without this permalink, there is no way to share a map with my settings.
