### ISSUE TITLE
members of parent relations all in route list

### ISSUE THREAD

**Issue by Hufkratzer** [lonvia/waymarked-trails-site#233]
Some time ago the members of parent relations were not in the route list but only listed as sections of the parent relation I think, and this was ok. Now they are all in the route list together with the parent relation (as far as the sections are in the visible map area). This may not be intended. Here is an example:

http://riding.waymarkedtrails.org/#routelist?map=9!51.7134!7.7646 shows:
![routelist](https://cloud.githubusercontent.com/assets/5958184/14590261/9bb4eff0-04f6-11e6-9e33-2986c0a21327.jpg)

sections of http://riding.waymarkedtrails.org/#route?id=4085740 are:
![sections](https://cloud.githubusercontent.com/assets/5958184/14590273/e33accfa-04f6-11e6-81a6-74e261415043.jpg)

**Comment by lonvia** [comment]
Child routes have always only been hidden when the child and parent routes both had a network tag and the network had the same value. That's also was http://riding.waymarkedtrails.org/help/rendering/hierarchies says.

Just checked in the old database and http://www.openstreetmap.org/relation/4086092 is certainly as top route in there. So the behavior has not changed with the update.

**Comment by Hufkratzer** [comment]
Why doesn't that work with superrelation http://riding.waymarkedtrails.org/#route?id=6147970 ?

The superrelation and all 3 children have network=nhn
(http://ra.osmsurround.org/searchRelation?name=Reiterpfad&network=nhn)
but http://riding.waymarkedtrails.org/#routelist?map=7!50.5274!9.9866 shows them all:
![superpfad1](https://cloud.githubusercontent.com/assets/5958184/14655992/5953b570-0685-11e6-8d0e-b66a3457c537.jpg)

And if I search for "reiterpfad" I get the superrelation and only one of the 3 children:
http://riding.waymarkedtrails.org/#search?query=reiterpfad&map=7!50.5274!9.7888
![superpfad2](https://cloud.githubusercontent.com/assets/5958184/14656006/6c88c32e-0685-11e6-867d-2e95ca537f51.jpg)

**Comment by lonvia** [comment]
It's an update issue. You've added the superroute after the parts. The top-level status of a relation is only set when it is changed. This will sort itself out when the subrelations are modified in some way the next time.
