### ISSUE TITLE
Rendering of some non-latin languages is broken

### ISSUE THREAD

**Issue by lonvia** [lonvia/waymarked-trails-site#234]
e.g. Korean here: http://hiking.waymarkedtrails.org/#?map=16!35.7289!127.9532

Need to find and install appropriate fonts.

**Comment by adonishi** [comment]
also broken in Japanese. e.g. http://hiking.waymarkedtrails.org/#?map=15!35.1529!139.6354

I guess you should use Pan-Unicode font like "Dronid font".
https://en.wikipedia.org/wiki/List_of_CJK_fonts
https://en.wikipedia.org/wiki/Droid_fonts



or define fallback fonts by Mapnik's FontSet tag.
https://github.com/mapnik/mapnik/wiki/FontSet
and replace all face-name by fontset-name.
https://github.com/mapnik/mapnik/wiki/TextSymbolizer#character-formatting-options

**Comment by lonvia** [comment]
Thanks for these pointers. Shields are fixed now. I still need to look into Mapnik FontSets for the names of the hiking posts.
