### ISSUE TITLE
Wrong length reported for Ramapo-Dunderberg Trail

### ISSUE THREAD

**Issue by iamkrzys** [lonvia/waymarked-trails-site#235]
I noticed that the reported length for Ramapo-Dunderberg trail is 322 km while the trail is really about 35 km long: http://hiking.waymarkedtrails.org/#route?id=5485397&map=12!41.2448!-74.0358

Also, the elevation profile does not show while Relation Analyzer claims the trail is continuous: http://ra.osmsurround.org/analyzeRelation?relationId=5485397&noCache=true&_noCache=on

This came up in a discussion with another OSM contributor who mentioned that lack of order in relation segments could be responsible for this.

Can anyone take a look and see what is happening here?  Tks!

**Comment by lonvia** [comment]
Some segments of this relation are duplicated in the database. My guess is that this is happening when a node in a segmented way gets updated. I need to write a test case that replicates the problem.

**Comment by lonvia** [comment]
I've pushed an [update to osgende](https://github.com/lonvia/osgende/commit/2c42f9f0618a49049282f46d3eb77cfd699dedb2) which will fix the problem. I'm not yet sure how to clean up the broken entries in the database (or whether to do it at all, the database will fix itself in time with incomming updates).

**Comment by iamkrzys** [comment]
Thanks very much for debugging and fixing this!  I noticed that for this relation two segments actually overlap on two adjacent nodes - see http://www.openstreetmap.org/way/369195399#map=19/41.27602/-74.00426 and http://www.openstreetmap.org/way/80515395#map=18/41.27597/-74.00446 which share http://www.openstreetmap.org/node/939277235 and 
http://www.openstreetmap.org/node/939277252

**Comment by lonvia** [comment]
Really fixed now and the database will be clean as well in an hour or two.
