### ISSUE TITLE
Elevation profile issues

### ISSUE THREAD

**Issue by kennykb** [lonvia/waymarked-trails-site#236]
I've been working on editing some regional trails in New York's Catskill Mountains, and I'm wondering what I need to do to make elevation profiles work for me. It seems to be pretty random what's happening.

Two examples that I can think of are Devil's Path (5461814) and Long Path (919642).

With Devil's Path, Waymarked Trails continues to grey out the elevation profile button, even though as far as I can tell, all the ways are continuous and listed in order. I realize that topology is important, and I've been pretty careful to ensure that each way ends on the same node where the next way starts. But Waymarked Trails still appears to have a problem with it, and I've not been able to figure out how to fix it.

With the Long Path, I expect to see no profile for the Schoharie, Albany, Schenectady and Saratoga County segments, because they're not fully mapped yet. My issue with Long Path is that I can't seem to control the direction in which elevation profiles get produced. On each of the segments, I've been careful to list the ways in order from south to north, but, again apparently at random, Waymarked Trails is producing the profiles in the opposite sequence.

I'm sure that I must be doing something wrong, but as nearly as I can tell, I'm following the instructions. Could you possibly enlighten me about how to fix this?

**Comment by jschleic** [comment]
For me it seems as if the database is screwed up. When downloading the [gpx](http://hiking.waymarkedtrails.org/api/details/relation/5461814/gpx), many points are duplicates and the route is cut into multiple `trkseg`'s. Is this somehow related to #213 ?

As a very simple example (or is that a different issue?), please also have a look at [6040616](http://cycling.waymarkedtrails.org/#route?id=6040616). That relation consists of four ways but your gpx export has one way twice. In my pbf exctract imported locally the relation is a single linestring:

<pre>
select GeometryType(geom) from cycling.routes where id=6040616;
 geometrytype 
--------------
 LINESTRING
(1 Zeile)
</pre>

Could there be an osgende update issue?

**Comment by jschleic** [comment]
@kennykb Currently there is no possibility to influence the direction. See #180 .

**Comment by kennykb** [comment]
OK, got it that there's no way to set the direction. That's unfortunate for a route that is big enough to need a superrelation (if the whole Long Path is made into one relation, it starts crashing JOSM), because it would be nice if the directions were at least consistent.

With Devil's Path  (5461814) - I'm not sure what you're talking about with 'my' GPX export. It's Waymarked Trails that's exporting to GPX, right? I'm looking at what appears in OpenStreetMap, and JOSM appears to think that the route is continuous, as do http://osmrm.openstreetmap.de/relation.jsp?id=5461814 and http://ra.osmsurround.org/analyzeRelation?relationId=5461814 . What should I be looking for?

**Comment by jschleic** [comment]
Yes, relation 5461814 is fine (as far as I can tell).
However it seems, that the representation in lonvias waymarked-trails-database is not okay. @lonvia Do you have any idea, what went wrong?

**Comment by lonvia** [comment]
These artifacts are essentially the same issue as #235. Due to a bug in the update scripts, some segments of the route appear multiple times in the segment table. I'm investigating this right now.

Route ordering is very high on my todo list. The plan is to follow the order in the relation as closely as possible. So please keep up the mapping you are doing right now and hopefully, the elevation profiles will be in the expected direction.

Closing here as duplicates for #235 and #180.
