### ISSUE TITLE
Network nodes for inline skating

### ISSUE THREAD

**Issue by colormapper** [lonvia/waymarked-trails-site#237]
Hello,

Near Delft, Netherlands is a network of inline skating routes consisting of numbered network nodes with connecting routes. This is a similar system as the cycling routes in the Netherlands.

[In the map](http://skating.waymarkedtrails.org/#?map=14!51.9553!4.3317) those network nodes are not visible. They are tagged with rin_ref (like the cycling nodes' rcn_ref). 

Is it possible to make the nodes visible?

Thanks in advance!

**Comment by lonvia** [comment]
Done. I've also added recognition of `network=rin`, so that the system now appears in exactly the same way as the hiking and cycling network.

**Comment by colormapper** [comment]
Thank you! 
This change made it easy to fix the errors in the network.
