### ISSUE TITLE
Switch between map variants on mobile

### ISSUE THREAD

**Issue by jschleic** [lonvia/waymarked-trails-site#251]
At low page widths the maplinks are hidden.
How is one supposed to switch between hiking, cycling, riding ... without the buttons?

**Comment by jschleic** [comment]
I can think of two possibilities at the moment:
* When the header bar is clicked / dragged, it expands so that the symbols become visible
* Add a section inside "Map settings" to switch to other map variants.

**Comment by lonvia** [comment]
The first suggestion sounds interesting. It would also be a good opportunity to switch to the SVG icons. That would allow to use bigger icons in the mobile view (accessibility for huge thumbs) and also look better on hires displays (mobile and desktop alike).

**Comment by Hufkratzer** [comment]
I would prefer if one could choose to see more than one type of routes at the same time, like in JOSM or www.gpsies.com for example. This would make the possibility to switch quickly less important and the buttons, checkboxes, or what it will be, may be placed in "map settings". A user will probably mostly want to see the same types of routes. (Just an idea, the other solution is probably easier).

Compare issue https://github.com/lonvia/waymarked-trails-site/issues/201

**Comment by drjoshua** [comment]
I've read the related post and I can't see the issue of the map icons being too big and too much space I the top bar. The bar itself is in place anyway. The icons could easily fit in the same bar height? Sitting on my mobile I would really want to be able to switch maps. Maybe change the CSS for some time and make a follow up?

**Comment by Hufkratzer** [comment]
Perhaps, as a temporary workaround, you can make the "Waymarked Trails" text on the left of the menu bar clickable so that it brings one back to the main menu which has buttons to select any of the different map types.

**Comment by drjoshua** [comment]
Or make the text "Waymarked Trails" a link that toogles between the different maps. One click changes from hiking to cycling, next to mtb...
