### ISSUE TITLE
Relation:route_master and Relation:superroute

### ISSUE THREAD

**Issue by wernerschka** [lonvia/waymarked-trails-site#271]
Please have a look at the following bicycle route:
https://www.openstreetmap.org/relation/28489
which is part of a collection of relations (in this case a "route_master", containing all variant routes of "Tauernradweg" ):
https://www.openstreetmap.org/relation/1775071
(in my opinion it's tagged by mistake as "type=route" instead of "type=route_master")

If I open the map for example here:
https://cycling.waymarkedtrails.org/#?map=17!48.1926!12.875
and click onto "Routes" on the bottom right just the route_master (1775071) NOT the single route (28489) is being listed.

A similar problem another route, sharing she same roads at the same location:
route: https://www.openstreetmap.org/relation/2770634
superroute: https://www.openstreetmap.org/relation/2749837
In the map just the icon "EV7" is displayed. If clicking onto "Routes" neither the route nor the superroute is listed.

For both cases: Is it possible if clicking onto a route in both cases to list single route + route_master/superroute? In my example 4 names should be listed by clicking onto the way.

**Comment by lonvia** [comment]
This is intentional behaviour. You can always get to the sections of the route by clicking on the main route and then opening the 'sections' section and choosing the route. The route is the "Tauernradweg", sections are not routes themselves.

**Comment by wernerschka** [comment]
Understood, good idea! Today even (superroute) "EV7" is being displayed within the "Routes" list again. Did you fix something? ;-)

**Comment by lonvia** [comment]
I messed up the database a bit yesterday but all should be back to normal now. Sorry about that.
