### ISSUE TITLE
Route list and route details in permalink

### ISSUE THREAD

**Issue by jschleic** [lonvia/waymarked-trails-site#72]
Currently the link references the current viewport and transparency slider settings. It would be nice to include the currently selected route in the permalink to show the route details window.

Example with LIM selected:
current link: http://cycling.lonvia.de/de/?zoom=10&lat=50.26759&lon=8.27337
proposed link: http://cycling.lonvia.de/de/relation/2944?zoom=10&lat=50.26759&lon=8.27337

**Comment by lonvia** [comment]
This is now implemented. The browser URL shows the status of the sidebar as well.
