### ISSUE TITLE
Always permalink / updating map link

### ISSUE THREAD

**Issue by dittaeva** [lonvia/waymarked-trails-site#90]
A recurrent problem I have when using waymarkedtrails.org (or Openstreetmap.org for that matter) is that if you navigate "back", you don't get back to the view you had last, but the view that you navigated to when you started browsing the site (from a permalink or simply the default starting location). This is at times, **very** annoying, and is something that seems to be addressed and fixed in [Modest Maps](http://modestmaps.com/) for [example](http://maps.stamen.com/#watercolor/12/37.7706/-122.3782), where the link will continuously update with the current location ("permalink").

I tried to search for this kind of functionality in OpenLayers to no avail, but I suppose my keywords weren't good enough because today I found that [geolocation.ws has this functionality](http://www.geolocation.ws/map/61.496914,7.128921/11/en).

**Comment by lonvia** [comment]
This is now implemented through the jquerymobile framework.
